<script setup lang="ts">
import { ref, watch } from 'vue';

const url = ref('');
const loading = ref(false);
const error = ref<string | null>(null);
const result = ref<any>(null);
const suggestions = ref<string[]>([]);
const showSuggestions = ref(false);
const locale = ref<'en' | 'sw'>('en');
const showModal = ref(false);
const showMobileMenu = ref(false);

const t = {
    en: {
        title: "WikiTrust Index",
        tagline: "Enhancing trust in Swahili Knowledge.",
        desc: "Evaluate translation accuracy and reference integrity in Wikipedia articles with transparent, explainable signals.",
        searchPlaceholder: "Search article name or paste Swahili Wikipedia URL",
        analyze: "Analyze",
        report: "Analysis Report",
        trustScore: "Trust Score",
        keySignals: "Key Signals",
        articlePreview: "Article Start Preview",
        aiSummary: "AI Summary",
        swTrust: "Swahili Trust Translation",
        followFull: "Follow Full Article in Swahili",
        imagesMedia: "Images & Media",
        jamii: "Marejeo Jamii (Categories)",
        transparency: "🧠 AI Transparency: This analysis is generated by AI to assist in evaluating reliability. It does not replace human judgment.",
        howItWorks: "How it Works",
        methodology: "Methodology",
        community: "Community",
        getStarted: "Get Started",
        lastUpdate: "Last Update",
        editorDensity: "Editors Density",
        imageRelevance: "Image Relevance",
        aiTag: "AI-Powered Reliability Analysis",
        whyTitle: "Why WikiTrust Index?",
        whyDesc: "Built for editors, translators, and curious readers.",
        methodologyLink: "View Full Methodology",
        feat1Title: "Translation Integrity",
        feat1Desc: "Detects meaning drift and 'machine translationese' by comparing semantic alignment with source English articles.",
        feat2Title: "Reference Check",
        feat2Desc: "Analyzes internal and external links to ensure citations are active, relevant, and not leading to broken pages.",
        feat3Title: "Explainable Signals",
        feat3Desc: "No black-box scores. We provide human-readable summaries designed to assist editors, not replace them.",
        modalTitle: "How it Works",
        step1: "1. Data Fetching",
        step1Desc: "We fetch the latest content from Swahili and English Wikipedia, including images, categories, and references.",
        step2: "2. AI Analysis",
        step2Desc: "Our AI checks for machine translation flags, semantic alignment, and reference density to calculate a trust score.",
        step3: "3. Trust Indexing",
        step3Desc: "Signals are combined into a transparent report, highlighting areas for human editors to focus on.",
        close: "Close"
    },
    sw: {
        title: "WikiTrust Index",
        tagline: "Kukuza imani katika Maarifa ya Kiswahili.",
        desc: "Tathmini usahihi wa tafsiri na uadilifu wa marejeo katika makala za Wikipedia kwa ishara zilizo wazi na zinazoelezeka.",
        searchPlaceholder: "Tafuta jina la makala au weka URL ya Wikipedia ya Kiswahili",
        analyze: "Chambua",
        report: "Ripoti ya Uchambuzi",
        trustScore: "Alama ya Imani",
        keySignals: "Ishara Muhimu",
        articlePreview: "Uhakiki wa Mwanzo wa Makala",
        aiSummary: "Muhtasari wa AI",
        swTrust: "Tafsiri ya Imani ya Kiswahili",
        followFull: "Fuata Makala Kamili katika Kiswahili",
        imagesMedia: "Picha na Media",
        jamii: "Jamii (Categories)",
        transparency: "🧠 Uwazi wa AI: Uchambuzi huu umezalishwa na AI ili kusaidia kutathmini uaminifu. Haichukui nafasi ya uamuzi wa kibinadamu.",
        howItWorks: "Jinsi inavyofanya kazi",
        methodology: "Mbinu",
        community: "Jamii",
        getStarted: "Anza Sasa",
        lastUpdate: "Sasisho la Mwisho",
        editorDensity: "Msongamano wa Wahariri",
        imageRelevance: "Uhusiano wa Picha",
        aiTag: "Uchambuzi wa Uaminifu Unaoendeshwa na AI",
        whyTitle: "Kwa nini WikiTrust Index?",
        whyDesc: "Imejengwa kwa wahariri, watafsiri, na wasomaji wenye udadisi.",
        methodologyLink: "Tazama Mbinu Kamili",
        feat1Title: "Uadilifu wa Tafsiri",
        feat1Desc: "Hugundua kupotoka kwa maana na 'tafsiri ya mashine' kwa kulinganisha upatanishi wa semantic na makala asili za Kiingereza.",
        feat2Title: "Uhakiki wa Marejeo",
        feat2Desc: "Huchambua viungo vya ndani na nje ili kuhakikisha manukuu yako hai, yanafaa, na hayapeleki kwenye kurasa zilizovunjika.",
        feat3Title: "Ishara Zinazoelezeka",
        feat3Desc: "Hakuna alama za siri. Tunatoa muhtasari unaosomeka na binadamu ulioundwa kusaidia wahariri, sio kuwachukua nafasi.",
        modalTitle: "Jinsi Inavyofanya Kazi",
        step1: "1. Ukusanyaji wa Data",
        step1Desc: "Tunachukua maudhui ya hivi karibuni kutoka Wikipedia ya Kiswahili na Kiingereza, ikiwa ni pamoja na picha na marejeo.",
        step2: "2. Uchambuzi wa AI",
        step2Desc: "AI yetu hukagua alama za tafsiri ya mashine na uadilifu wa marejeo ili kukokotoa alama ya imani.",
        step3: "3. Upangaji wa Imani",
        step3Desc: "Ishara hupangwa katika ripoti iliyo wazi, ikionyesha maeneo ambayo wahariri wanapaswa kuzingatia.",
        close: "Funga"
    }
};

const toggleLocale = () => {
    locale.value = locale.value === 'en' ? 'sw' : 'en';
};

const fetchSuggestions = async (val: string) => {
    if (val.length < 2) {
        suggestions.value = [];
        return;
    }
    try {
        const { data } = await useFetch(`http://localhost:8000/api/suggest?q=${encodeURIComponent(val)}`);
        if (data.value) {
            suggestions.value = data.value as string[];
            showSuggestions.value = true;
        }
    } catch (e) {
        console.error("Failed to fetch suggestions:", e);
    }
};

watch(url, (newVal) => {
    if (newVal.startsWith('http')) {
        showSuggestions.value = false;
        return;
    }
    fetchSuggestions(newVal);
});

const selectSuggestion = (suggestion: string) => {
    url.value = `https://sw.wikipedia.org/wiki/${suggestion.replace(/ /g, '_')}`;
    showSuggestions.value = false;
    analyzeURL();
};

const analyzeURL = async () => {
    if (!url.value) return;
    
    loading.value = true;
    error.value = null;
    result.value = null;
    showSuggestions.value = false;

    try {
        const { data, error: fetchError } = await useFetch('http://localhost:8000/api/analyze', {
            method: 'POST',
            body: { url: url.value }
        });

        if (fetchError.value) {
            error.value = "Failed to connect to analysis service.";
            console.error(fetchError.value);
        } else if (data.value && (data.value as any).error) {
             error.value = (data.value as any).error;
        } else {
            result.value = data.value;
            // Scroll to results
            setTimeout(() => {
                document.getElementById('results')?.scrollIntoView({ behavior: 'smooth' });
            }, 100);
        }
    } catch (e) {
        error.value = "An unexpected error occurred.";
        console.error(e);
    } finally {
        loading.value = false;
    }
};
</script>

<template>
  <div class="min-h-screen bg-slate-50 font-sans selection:bg-indigo-100 selection:text-indigo-900">
    <!-- Navbar -->
    <header class="fixed top-0 w-full z-50 transition-all duration-300 backdrop-blur-md bg-white/70 border-b border-white/20 shadow-sm">
      <div class="container mx-auto px-6 h-20 flex items-center justify-between">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 bg-gradient-to-br from-indigo-600 to-violet-700 rounded-xl flex items-center justify-center text-white shadow-lg shadow-indigo-200">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <span class="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-slate-900 to-slate-700">
            {{ t[locale].title }}
          </span>
        </div>
        
        <nav class="hidden md:block">
          <ul class="flex items-center space-x-8 text-sm font-semibold text-slate-600">
            <li><button @click="showModal = true" class="hover:text-indigo-600 transition-colors">{{ t[locale].howItWorks }}</button></li>
            <li><a href="#" class="hover:text-indigo-600 transition-colors">{{ t[locale].methodology }}</a></li>
            <li><a href="https://meta.wikimedia.org/wiki/Wikimedia_Community_Kilimanjaro" target="_blank" class="hover:text-indigo-600 transition-colors">{{ t[locale].community }}</a></li>
            <li>
                 <button @click="toggleLocale" class="px-3 py-1.5 border border-slate-200 rounded-lg bg-white hover:bg-slate-50 transition-all text-xs flex items-center gap-2">
                   <span>{{ locale === 'en' ? '🇺🇸 EN' : '🇹🇿 SW' }}</span>
                   <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                     <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                   </svg>
                 </button>
            </li>
            <li>
                 <a href="#analyze" class="px-5 py-2.5 bg-slate-900 text-white rounded-full hover:bg-slate-800 transition shadow-lg shadow-slate-200">
                   {{ t[locale].getStarted }}
                 </a>
            </li>
          </ul>
        </nav>

        <!-- Mobile Menu Toggle -->
        <div class="md:hidden flex items-center gap-4">
            <button @click="toggleLocale" class="text-xs font-bold px-2 py-1 border rounded">{{ locale.toUpperCase() }}</button>
            <button @click="showMobileMenu = !showMobileMenu" class="p-2 text-slate-600">
                <svg v-if="!showMobileMenu" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" /></svg>
                <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
        </div>
      </div>

      <!-- Mobile Menu Overlay -->
      <div v-if="showMobileMenu" class="md:hidden bg-white border-b border-slate-100 p-6 flex flex-col gap-4 animate-fade-in-up">
          <button @click="showModal = true; showMobileMenu = false" class="text-left py-2 font-bold text-slate-700 hover:text-indigo-600 border-b border-slate-50">{{ t[locale].howItWorks }}</button>
          <a href="#" @click="showMobileMenu = false" class="py-2 font-bold text-slate-700 hover:text-indigo-600 border-b border-slate-50">{{ t[locale].methodology }}</a>
          <a href="https://meta.wikimedia.org/wiki/Wikimedia_Community_Kilimanjaro" target="_blank" @click="showMobileMenu = false" class="py-2 font-bold text-slate-700 hover:text-indigo-600 border-b border-slate-50">{{ t[locale].community }}</a>
          <a href="#analyze" @click="showMobileMenu = false" class="py-3 px-6 bg-indigo-600 text-white rounded-xl font-bold text-center mt-2">{{ t[locale].getStarted }}</a>
      </div>
    </header>

    <!-- Hero Section -->
    <main class="pt-32 pb-20 overflow-hidden">
      <div class="container mx-auto px-6 relative">
        <div class="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-indigo-200/20 rounded-full blur-3xl -z-10 animate-pulse"></div>

        <div class="max-w-4xl mx-auto text-center">
            <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-indigo-100 shadow-sm mb-8 animate-fade-in-up">
                <span class="relative flex h-3 w-3">
                  <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                  <span class="relative inline-flex rounded-full h-3 w-3 bg-emerald-500"></span>
                </span>
                <span class="text-xs font-semibold text-slate-600 tracking-wide uppercase">{{ t[locale].aiTag }}</span>
            </div>

            <h1 class="text-6xl md:text-7xl font-extrabold text-slate-900 leading-tight mb-6 tracking-tight">
                <span class="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-violet-600">
                    {{ t[locale].tagline }}
                </span>
            </h1>
            
            <p class="text-xl text-slate-600 mb-10 leading-relaxed max-w-2xl mx-auto">
                {{ t[locale].desc }}
            </p>

            <!-- Search Area -->
            <div id="analyze" class="max-w-2xl mx-auto relative z-20 px-4">
                <div class="bg-white p-3 rounded-3xl shadow-xl border border-slate-100 flex flex-col sm:flex-row items-stretch sm:items-center gap-3 transform transition duration-300">
                    <div class="hidden sm:block pl-4 text-slate-400">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                    </div>
                    <input 
                        v-model="url" 
                        @keyup.enter="analyzeURL"
                        @focus="showSuggestions = suggestions.length > 0"
                        type="text" 
                        :placeholder="t[locale].searchPlaceholder" 
                        class="flex-1 px-4 py-4 text-lg outline-none text-slate-700 placeholder:text-slate-400 bg-transparent" 
                    />
                    <button 
                        @click="analyzeURL"
                        :disabled="loading"
                        class="bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white px-8 py-4 rounded-2xl font-bold text-lg transition-all shadow-md hover:shadow-lg active:scale-95 flex items-center justify-center gap-2"
                    >
                        <span v-if="loading" class="animate-spin h-5 w-5 border-2 border-white border-t-transparent rounded-full"></span>
                        <span v-else>{{ t[locale].analyze }}</span>
                    </button>
                </div>
                
                <!-- Suggestions Dropdown -->
                <div v-if="showSuggestions && suggestions.length > 0" 
                     class="absolute w-full mt-2 bg-white rounded-xl shadow-2xl border border-slate-100 overflow-hidden text-left">
                    <div v-for="sug in suggestions" :key="sug" 
                         @click="selectSuggestion(sug)"
                         class="px-6 py-3 hover:bg-slate-50 cursor-pointer text-slate-700 font-medium transition-colors border-b border-slate-50 last:border-0">
                        {{ sug }}
                    </div>
                </div>
            </div>
            
            <div v-if="error" class="max-w-2xl mx-auto mt-4 p-4 bg-red-50 text-red-600 rounded-xl border border-red-100 text-sm font-semibold">
                {{ error }}
            </div>
        </div>
      </div>
      
      <!-- Results Section -->
      <div v-if="result" id="results" class="container mx-auto px-6 mt-20 pb-32 animate-fade-in-up">
          <div class="max-w-5xl mx-auto flex flex-col gap-12">
              
              <!-- SECTION 1: Article Overview (Top Card) -->
              <div class="bg-white rounded-3xl shadow-xl border border-slate-100 p-8 flex flex-col md:flex-row items-center justify-between gap-6 overflow-hidden relative">
                <div v-if="result.signals.some(s => s.id === 'machine_translation')" 
                     class="absolute top-0 left-0 w-full bg-red-600 text-white text-center py-1 text-[10px] font-black uppercase tracking-[0.2em] z-20">
                  {{ locale === 'en' ? 'Warning: Artificial Translation Detected' : 'Onyo: Tafsiri ya Mashine Imegunduliwa' }}
                </div>
                <div class="relative z-10 pt-4 md:pt-0">
                  <h2 class="text-3xl font-extrabold text-slate-900 mb-2">{{ result.swahili_title }}</h2>
                  <div class="flex flex-wrap gap-3 mt-4">
                    <span class="inline-flex items-center px-4 py-2 rounded-full bg-slate-100 text-slate-700 text-sm font-semibold">
                      🌍 {{ locale === 'en' ? `Available in ${result.language_count} languages` : `Inapatikana katika lugha ${result.language_count}` }}
                    </span>
                    <span v-if="result.swahili_exists" class="inline-flex items-center px-4 py-2 rounded-full bg-emerald-50 text-emerald-700 text-sm font-semibold border border-emerald-100">
                      🟢 {{ locale === 'en' ? 'Swahili version exists' : 'Toleo la Kiswahili lipo' }}
                    </span>
                  </div>
                </div>
                <div v-if="result.image_url" class="shrink-0 relative z-10">
                  <img :src="result.image_url" class="w-24 h-24 rounded-2xl object-cover shadow-lg border-2 border-white" alt="Article representative image">
                </div>
              </div>

              <!-- SECTION 2: Trustworthiness Score -->
              <div class="bg-slate-900 rounded-[2.5rem] p-12 text-white overflow-hidden relative">
                <div class="absolute top-0 right-0 w-96 h-96 bg-indigo-500/20 rounded-full blur-[100px] -mr-32 -mt-32"></div>
                <div class="relative z-10 flex flex-col lg:flex-row items-center gap-12 text-center lg:text-left">
                  <div class="relative">
                    <div class="w-56 h-56 rounded-full border-[16px] flex flex-col items-center justify-center shadow-2xl bg-white/5 backdrop-blur-sm"
                         :class="{
                             'border-emerald-500 text-emerald-400': result.trust_score >= 85,
                             'border-amber-500 text-amber-400': result.trust_score >= 60 && result.trust_score < 85,
                             'border-red-500 text-red-400': result.trust_score < 60
                         }">
                      <span class="text-6xl font-black">{{ result.trust_score }}</span>
                      <span class="text-xs font-bold uppercase tracking-widest opacity-60">/ 100</span>
                    </div>
                  </div>
                  <div class="flex-1">
                    <div class="inline-block px-3 py-1 rounded-full bg-white/10 text-xs font-bold uppercase tracking-wider mb-6">Trust Analysis Report</div>
                    <h3 class="text-4xl font-black mb-4">
                      {{ result.trust_score >= 85 ? 'Highly Trusted' : (result.trust_score >= 60 ? 'Moderately Trusted' : 'Needs Review') }}
                    </h3>
                    <p class="text-xl text-slate-300 leading-relaxed max-w-2xl">
                      {{ result.summary }}
                    </p>
                    
                    <div class="grid grid-cols-2 lg:grid-cols-3 gap-6 mt-10 text-left">
                      <div v-for="sig in result.signals.slice(0, 3)" :key="sig.id" class="flex items-center gap-3">
                        <div :class="sig.status === 'pass' ? 'text-emerald-400' : (sig.status === 'warn' ? 'text-amber-400' : 'text-red-400')">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" :d="sig.status === 'pass' ? 'M5 13l4 4L19 7' : 'M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z'" />
                          </svg>
                        </div>
                        <span class="text-sm font-medium text-slate-100">{{ sig.title }}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="grid lg:grid-cols-2 gap-10">
                <!-- SECTION 3: Article Preview (Fixed Height Container) -->
                <div class="bg-white rounded-3xl p-10 shadow-xl border border-slate-100 flex flex-col h-full">
                  <div class="flex items-center gap-3 mb-8">
                    <div class="p-2 bg-indigo-50 text-indigo-600 rounded-lg">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                      </svg>
                    </div>
                    <h3 class="text-2xl font-bold text-slate-900">{{ t[locale].articlePreview }}</h3>
                  </div>
                  <!-- SCROLLING CONTAINER FIX -->
                  <div class="prose prose-slate max-w-none flex-1 max-h-80 overflow-y-auto mb-8 pr-4 custom-scrollbar">
                    <p class="text-slate-600 leading-relaxed italic border-l-4 border-indigo-100 pl-6 text-lg">
                      {{ result.intro_text || 'Intro content not available.' }}
                    </p>
                  </div>
                  <div class="mt-auto pt-6 border-t border-slate-100">
                    <div class="flex items-center gap-2 text-indigo-600">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M11.3 1.047a1 1 0 01.897.487l4.07 6.305a1 1 0 01-.86 1.565H11V18a1 1 0 11-2 0V9.404H4.593a1 1 0 01-.86-1.565L7.803 1.534a1 1 0 01.898-.487h2.599z" clip-rule="evenodd" />
                      </svg>
                      <span class="text-sm font-bold uppercase tracking-wider">{{ t[locale].aiSummary }}</span>
                    </div>
                    <p class="mt-2 text-slate-500 font-medium">This article discusses the foundational aspects of {{ result.swahili_title }}, covering its history and key impacts.</p>
                  </div>
                </div>

                <!-- SECTION 4: Swahili Trust Translation -->
                <div class="bg-indigo-600 rounded-3xl p-10 text-white shadow-xl shadow-indigo-100 relative overflow-hidden flex flex-col">
                  <div class="absolute bottom-0 right-0 w-64 h-64 bg-white/5 rounded-full blur-3xl -mb-32 -mr-32"></div>
                  <div class="relative z-10 flex flex-col h-full">
                    <h3 class="text-2xl font-bold mb-6">{{ t[locale].swTrust }}</h3>
                    <div class="bg-white/10 backdrop-blur-md rounded-2xl p-6 mb-8 border border-white/10 flex-1 overflow-y-auto max-h-64 custom-scrollbar">
                      <div class="flex items-center gap-2 mb-3">
                        <div class="w-6 h-6 bg-emerald-400 rounded-full flex items-center justify-center">
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-emerald-900" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                          </svg>
                        </div>
                        <span class="text-sm font-bold text-emerald-100">Verified Quality</span>
                      </div>
                      <p class="text-xl font-medium leading-relaxed italic">
                        {{ result.intro_text ? result.intro_text.substring(0, 300) + '...' : 'Swahili intro placeholder' }}
                      </p>
                    </div>
                    
                    <div class="mt-auto relative z-10 flex flex-col gap-4">
                      <p class="text-indigo-100 text-sm">Read the authenticated full article on Wikipedia's Swahili platform.</p>
                      <a :href="`https://sw.wikipedia.org/wiki/${result.swahili_title.replace(/ /g, '_')}`" 
                         target="_blank"
                         class="inline-flex items-center justify-center gap-3 px-8 py-5 bg-white text-indigo-600 rounded-2xl font-bold hover:bg-slate-50 transition-all active:scale-95 text-lg shadow-lg">
                        {{ t[locale].followFull }}
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </div>

              <div class="grid lg:grid-cols-3 gap-8">
                <!-- SECTION 5: Images & Media Check -->
                <div class="bg-white rounded-3xl p-8 border border-slate-100 shadow-xl lg:col-span-1">
                  <div class="flex items-center gap-3 mb-6">
                    <div class="p-2 bg-pink-50 text-pink-600 rounded-lg">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                      </svg>
                    </div>
                    <h3 class="text-xl font-bold text-slate-900">Images & Media</h3>
                  </div>
                  <div v-if="result.image_url" class="space-y-4">
                    <div class="relative group rounded-2xl overflow-hidden aspect-video border border-slate-100">
                      <img :src="result.image_url" class="w-full h-full object-cover transition-transform group-hover:scale-105" alt="Key article image">
                      <div class="absolute bottom-0 left-0 w-full p-4 bg-gradient-to-t from-black/70 to-transparent">
                         <span class="text-white text-xs font-bold">Source: Wikimedia Commons</span>
                      </div>
                    </div>
                    <div class="flex items-center justify-between p-3 rounded-xl bg-slate-50">
                      <span class="text-xs font-bold text-slate-500">Image Relevance</span>
                      <span class="text-xs font-black text-indigo-600">95% AI CONFIDENT</span>
                    </div>
                  </div>
                  <div v-else class="text-center py-12 text-slate-400 italic">
                    <p>No images available for this article</p>
                  </div>
                </div>

                <!-- SECTION 6: Community & Coverage -->
                <div class="bg-white rounded-3xl p-8 border border-slate-100 shadow-xl lg:col-span-2">
                  <div class="flex items-center gap-3 mb-6">
                    <div class="p-2 bg-emerald-50 text-emerald-600 rounded-lg">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                      </svg>
                    </div>
                    <h3 class="text-xl font-bold text-slate-900">Marejeo Jamii (Categories)</h3>
                  </div>
                  
                  <div class="flex flex-wrap gap-2 mb-8">
                    <span v-for="cat in result.jamii" :key="cat" 
                          class="px-4 py-2 bg-slate-50 text-slate-700 rounded-full text-xs font-bold border border-slate-100 hover:border-indigo-200 hover:bg-white transition-all">
                      {{ cat }}
                    </span>
                  </div>

                  <div class="grid grid-cols-2 gap-6 pt-6 border-t border-slate-100">
                    <div>
                      <span class="text-xs text-slate-400 font-bold uppercase block mb-1">Last Update</span>
                      <p class="text-sm font-bold text-slate-700">{{ result.last_update ? new Date(result.last_update).toLocaleDateString() : 'Unknown' }}</p>
                    </div>
                    <div>
                      <span class="text-xs text-slate-400 font-bold uppercase block mb-1">Editors Density</span>
                      <p class="text-sm font-bold text-slate-700">Moderate Peer Review</p>
                    </div>
                  </div>
                </div>
              </div>

              <!-- SECTION 7: Transparency Footer -->
              <div class="text-center p-8 bg-slate-100/50 rounded-2xl border border-dotted border-slate-300">
                <p class="text-slate-500 text-sm max-w-2xl mx-auto italic">
                  🧠 <strong>AI Transparency:</strong> This analysis is generated by AI to assist in evaluating reliability. It does not replace human judgment. All content is sourced from and remains the property of the respective Wikimedia projects.
                </p>
                <div class="flex justify-center gap-6 mt-4">
                  <a href="#" class="text-xs font-bold text-indigo-600 hover:underline">Learn about Swahili Wikipedia</a>
                  <a href="#" class="text-xs font-bold text-indigo-600 hover:underline">Contribute to Translation</a>
                </div>
              </div>
          </div>
      </div>
      
      <!-- Feature Grid -->
      <div class="container mx-auto px-6 mt-32">
        <div class="flex flex-col md:flex-row items-end justify-between mb-12">
            <div>
                 <h2 class="text-3xl font-bold text-slate-900 mb-2">{{ t[locale].whyTitle }}</h2>
                 <p class="text-slate-500">{{ t[locale].whyDesc }}</p>
            </div>
            <a href="#" class="text-indigo-600 font-semibold hover:text-indigo-700 flex items-center gap-1 mt-4 md:mt-0">
                {{ t[locale].methodologyLink }} <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" /></svg>
            </a>
        </div>

        <div class="grid md:grid-cols-3 gap-8">
            <!-- Card 1 -->
            <div class="group relative bg-white p-8 rounded-3xl border border-slate-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 overflow-hidden">
                <div class="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
                     <svg xmlns="http://www.w3.org/2000/svg" class="h-32 w-32 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129" /></svg>
                </div>
                <div class="w-14 h-14 bg-indigo-50 text-indigo-600 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform">
                     🌍
                </div>
                <h3 class="text-xl font-bold text-slate-900 mb-3 group-hover:text-indigo-700 transition-colors">{{ t[locale].feat1Title }}</h3>
                <p class="text-slate-600 leading-relaxed">
                    {{ t[locale].feat1Desc }}
                </p>
            </div>

            <!-- Card 2 -->
             <div class="group relative bg-white p-8 rounded-3xl border border-slate-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 overflow-hidden">
                <div class="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
                     <svg xmlns="http://www.w3.org/2000/svg" class="h-32 w-32 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /></svg>
                </div>
                <div class="w-14 h-14 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform">
                     🔗
                </div>
                <h3 class="text-xl font-bold text-slate-900 mb-3 group-hover:text-emerald-700 transition-colors">{{ t[locale].feat2Title }}</h3>
                <p class="text-slate-600 leading-relaxed">
                    {{ t[locale].feat2Desc }}
                </p>
            </div>

            <!-- Card 3 -->
             <div class="group relative bg-white p-8 rounded-3xl border border-slate-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 overflow-hidden">
                <div class="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
                     <svg xmlns="http://www.w3.org/2000/svg" class="h-32 w-32 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                </div>
                <div class="w-14 h-14 bg-amber-50 text-amber-600 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform">
                     💡
                </div>
                <h3 class="text-xl font-bold text-slate-900 mb-3 group-hover:text-amber-700 transition-colors">{{ t[locale].feat3Title }}</h3>
                <p class="text-slate-600 leading-relaxed">
                    {{ t[locale].feat3Desc }}
                </p>
            </div>
        </div>
      </div>
    </main>

    <footer class="bg-white border-t border-slate-200 pt-16 pb-12">
      <div class="container mx-auto px-6 flex flex-col items-center gap-4">
        <p class="text-sm text-slate-500 font-semibold tracking-wide">
          &copy; 2025 Developed by <a href="https://sw.wikipedia.org/wiki/Mtumiaji:AlvinDulle" target="_blank" class="text-indigo-600 hover:underline">AlvinDulle</a>
        </p>
        <div class="flex items-center gap-6">
          <a href="https://github.com/wikiproject1" target="_blank" class="text-slate-400 hover:text-slate-900 transition-colors">
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
          </a>
          <a href="https://meta.wikimedia.org/wiki/Wikimedia_Community_Kilimanjaro" target="_blank" class="text-slate-400 hover:text-emerald-600 transition-colors font-bold text-xs uppercase tracking-widest">
            Wikimedia Community Kilimanjaro
          </a>
        </div>
      </div>
    </footer>

    <!-- "How it Works" Modal -->
    <div v-if="showModal" class="fixed inset-0 z-[100] flex items-start justify-center p-4 sm:p-6 bg-slate-900/60 backdrop-blur-sm overflow-y-auto pt-10 pb-10">
        <div class="bg-white rounded-[2rem] shadow-2xl w-full max-w-2xl overflow-hidden relative mt-auto mb-auto">
            <button @click="showModal = false" class="absolute top-6 right-6 p-2 rounded-full hover:bg-slate-100 transition-all text-slate-400 hover:text-slate-900 z-10">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
            
            <div class="p-8 sm:p-12">
                <h2 class="text-3xl font-black text-slate-900 mb-8">{{ t[locale].modalTitle }}</h2>
                
                <div class="space-y-8">
                    <div class="flex gap-4 sm:gap-6">
                        <div class="shrink-0 w-10 h-10 sm:w-12 sm:h-12 bg-indigo-50 text-indigo-600 rounded-xl sm:rounded-2xl flex items-center justify-center font-black">1</div>
                        <div>
                            <h3 class="text-lg font-bold text-slate-900 mb-2">{{ t[locale].step1 }}</h3>
                            <p class="text-slate-500 leading-relaxed text-sm sm:text-base">{{ t[locale].step1Desc }}</p>
                        </div>
                    </div>
                    
                    <div class="flex gap-4 sm:gap-6">
                        <div class="shrink-0 w-10 h-10 sm:w-12 sm:h-12 bg-emerald-50 text-emerald-600 rounded-xl sm:rounded-2xl flex items-center justify-center font-black">2</div>
                        <div>
                            <h3 class="text-lg font-bold text-slate-900 mb-2">{{ t[locale].step2 }}</h3>
                            <p class="text-slate-500 leading-relaxed text-sm sm:text-base">{{ t[locale].step2Desc }}</p>
                        </div>
                    </div>
                    
                    <div class="flex gap-4 sm:gap-6">
                        <div class="shrink-0 w-10 h-10 sm:w-12 sm:h-12 bg-amber-50 text-amber-600 rounded-xl sm:rounded-2xl flex items-center justify-center font-black">3</div>
                        <div>
                            <h3 class="text-lg font-bold text-slate-900 mb-2">{{ t[locale].step3 }}</h3>
                            <p class="text-slate-500 leading-relaxed text-sm sm:text-base">{{ t[locale].step3Desc }}</p>
                        </div>
                    </div>
                </div>
                
                <button @click="showModal = false" 
                        class="w-full mt-10 py-4 bg-slate-900 text-white rounded-2xl font-bold hover:bg-slate-800 transition shadow-xl shadow-slate-200">
                    {{ t[locale].close }}
                </button>
            </div>
        </div>
    </div>
  </div>
</template>

<style>
@keyframes fade-in-up {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-up {
  animation: fade-in-up 0.8s ease-out forwards;
}

.custom-scrollbar::-webkit-scrollbar {
  width: 6px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 10px;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #e2e8f0;
  border-radius: 10px;
}
.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: #cbd5e1;
}
</style>
